### ISSUE TITLE
Static files missing in distributed package

### ISSUE THREAD

**Issue by msmart** [wildfish/django-pipelines#1]
I installed pipelines as described in the quickstart. However, the static files are missing from the package. 

To fix this, I manually copied them from the git repo.

![image](https://github.com/wildfish/django-pipelines/assets/85249/279427c1-ad24-4710-847f-742a125eefb7)

Thanks for putting this project out there!

**Comment by StuartMacKay** [comment]
Thanks for reporting this. There was a typo in the manifest which stopped the static files from being included.
